### PR TITLE
Fix collab server formidable

### LINKED ISSUE #47: Collab server build issue
When running Collab server, shows the error "TypeError: r is not a function".

### LINKED ISSUE #49: Collaboration inconsistencies issue

### LINKED ISSUE #50: Licit Editor - Toolbar is poorly organized

### LINKED ISSUE #51: Licit Editor - Cannot reference image using fully qualified URL

### LINKED ISSUE #52: Licit Editor - Editor allows changing font sizes when disabled
1. Editor allows changing font sizes when editor in disabled state.
2. Horizontal Line button is not greyed out when editor is disabled.

### PR DESCRIPTION
**Pull request by firmusoft**
1. New collab server reusing base PM collab server to resolve collaboration inconsistencies.
2. New Image Server to deal image upload.
3. FIX: Errors with formidable when bundling collab server.
4. FIX: Licit Editor - Toolbar is poorly organized.
5. Replaced chanzuckerberg/prosemirror-tables with ProseMirror/prosemirror-tables.
6. Licit Editor - Cannot reference image using fully qualified URL
7. Editor - Editor allows changing font sizes when disabled
8. Licit Editor - Horizontal Line button is not greyed out when editor is disabled.
9. Modified README.md file to include commands to run image server for upload image.

### CODE REVIEW

File: utils/build_licit_collab_server.js [hunk 1]
```diff
@@ -31,7 +37,7 @@ const config = {
     ],
   },
   plugins: [
-    new FlowWebpackPlugin(),
+    // new FlowWebpackPlugin(),
```
Comment (melgish) [inline utils/build_licit_collab_server.js]: Doesn't removing this disable type checking for the whole build?

File: utils/build_image_server.js [hunk 2]
```diff
@@ -34,14 +34,15 @@ const server =
   new WebpackDevServer(compiler, {
     hot: true,
     contentBase: path.join(__dirname, '../servers/image'),
-    headers: {  'Access-Control-Allow-Origin': '*' },      
+    headers: {
```
Comment (melgish) [inline utils/build_image_server.js]: Use a library instead of doing this yourself.  Try https://www.npmjs.com/package/cors

File: licit/server/collab/server.js [hunk 3]
```diff
@@ -0,0 +1,187 @@
...
+import {getInstance, instanceInfo} from "./instance"
+
+const router = new Router();
+
+function handleCollabRequest(req, resp) {  
+  if(!router.resolve(req, resp)) {  
+    const method = req.method.toUpperCase();
+    if (method === 'OPTIONS') {
+      const headers = {
+        'Access-Control-Allow-Origin': '*',
```
Comment (melgish) [inline licit/server/collab/server.js:16]: Again, there are libraries for this

**Review by melgish — APPROVED** [review]

File: utils/build_licit_collab_server.js (hunk 1 above)
Comment (firmusoft) [reply utils/build_licit_collab_server.js]: There were some flow validation errors in PM tables and hence we had commented out earlier, thinking that we will deal later as it is not a blocker at runtime. But got removed accidentally on the way as it was commented out. Also this was taking too much time to build. Now put in back and to run only in development mode. Shall try to resolve those issues if something that needs to be done on our side or else post an issue in PM discussion/github as well.

File: utils/build_image_server.js (hunk 2 above)
Comment (firmusoft) [reply utils/build_image_server.js]: Thought of handling our own cors headers to avoid extra dependency. We have added this cors package which looks like it takes care of all CORS related things. Thanks!

File: licit/server/collab/server.js (hunk 3 above)
Comment (firmusoft) [reply licit/server/collab/server.js:16]: Here we left it like this as we are not using express here.
